In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits

import os

In [2]:
hdul = fits.open("../eROSITA_5.0x5.0/Phox/phlist_140.fits")
redshift = hdul[0].header["REDSHIFT"]
redshift

0.032637492755919

In [3]:
data = hdul[2].data
table = pd.DataFrame(data[:])
table["REDSHIFT"] = redshift
print(table.to_numpy())

[[ 0.1747205  12.34507561  8.04138279  0.03263749]
 [ 0.19680159 12.36287975  8.04604626  0.03263749]
 [ 0.17229494 12.45425797  7.61272335  0.03263749]
 ...
 [ 0.72353977  8.36527824 11.50980282  0.03263749]
 [ 1.39314687  8.35939693 11.53186512  0.03263749]
 [ 3.37372637  8.34757519 11.52863026  0.03263749]]


In [4]:
a = table.to_numpy()[0:2]
b = table.to_numpy()[2:4]
np.concatenate((a,b))

array([[ 0.1747205 , 12.34507561,  8.04138279,  0.03263749],
       [ 0.19680159, 12.36287975,  8.04604626,  0.03263749],
       [ 0.17229494, 12.45425797,  7.61272335,  0.03263749],
       [ 0.19681488, 12.48889256,  7.57853699,  0.03263749]])

In [5]:
data["ENERGY"]

array([0.1747205 , 0.19680159, 0.17229494, ..., 0.72353977, 1.3931469 ,
       3.3737264 ], dtype=float32)

In [6]:
data.field("RA").mean()

10.602292

In [7]:
data.field("DEC").mean()

10.323925

In [21]:
wd = 'eROSITA_5.0x5.0/Phox/'
mylist = sorted(os.listdir("/Users/mac/work/clusters/"+wd))

mylist = [item for item in mylist if item[:6] == "phlist"]
#print(wd+str(mylist))

table_merged = [np.zeros((4))]
print(table_merged)

length = 0

for item in mylist:
    if item[:6] == "phlist":
        
        hdul = fits.open(wd+item)
        redshift = hdul[0].header["REDSHIFT"]
        
        data = hdul[2].data
        table = pd.DataFrame(data[:])
        table["REDSHIFT"] = redshift
        
        table_array = table.to_numpy()
        length = length + len(table_array)
        
        table_merged = np.concatenate((table_merged, table_array))
        
        #print(wd+item, )
        #print(table.to_numpy())
        hdul.close()
        
print(type(table_merged[1:]))
print(length)

[array([0., 0., 0., 0.])]
<class 'numpy.ndarray'>
2534310


In [36]:
pd.DataFrame(table_merged, columns=["ENERGY", "RA", "DEC", "REDSHIFT"]).drop(0).to_csv('phlist_merged.csv', index=False)